modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/pcal43/fastback"
license = "GPL2"

[[mods]]
modId = "fastback"
version = "0.17.4+1.20.6-prerelease"
displayName = "Fast Backups"
authors = "pcal"
description = '''
Fast, incremental world backups powered by Git.
https://pcal43.github.io/fastback/
'''
logoFile = "fastback-icon.png"

[[dependencies.fastback]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.fastback]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.6"
ordering = "NONE"
side = "CLIENT"
